Update main_zenithbank.yml

diff --git a/.github/workflows/main_zenithbank.yml b/.github/workflows/main_zenithbank.yml
--- a/.github/workflows/main_zenithbank.yml
+++ b/.github/workflows/main_zenithbank.yml
@@ -18,13 +18,21 @@ jobs:
         with:
           python-version: '3.12'
 
+      - name: Confirm Python version and location
+        run: |
+          python --version
+          which python
+
       - name: Create virtual environment and install dependencies
         run: |
           python -m venv venv
+          if [ ! -d "venv" ]; then
+            echo "Virtual environment creation failed"
+            exit 1
+          fi
+          ls -la  # List directory to check venv created
           source venv/bin/activate
           pip install -r ./server/requirements.txt
-        env:
-          pythonLocation: /opt/hostedtoolcache/Python/3.12.7/x64
 
       - name: Run Flask tests
         run: |
